# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fullme_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fullme_window(object):
    def setupUi(self, fullme_window):
        fullme_window.setObjectName("fullme_window")
        fullme_window.resize(342, 445)
        fullme_window.setMinimumSize(QtCore.QSize(342, 445))
        fullme_window.setMaximumSize(QtCore.QSize(342, 445))
        self.verticalLayoutWidget = QtWidgets.QWidget(fullme_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 440))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fullme_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fullme_1.setText("")
        self.label_fullme_1.setPixmap(QtGui.QPixmap(":/imgs/images/fullme/fullme1.jpg"))
        self.label_fullme_1.setScaledContents(True)
        self.label_fullme_1.setObjectName("label_fullme_1")
        self.verticalLayout.addWidget(self.label_fullme_1)
        self.label_fullme_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fullme_2.setText("")
        self.label_fullme_2.setPixmap(QtGui.QPixmap(":/imgs/images/fullme/fullme2.jpg"))
        self.label_fullme_2.setScaledContents(True)
        self.label_fullme_2.setObjectName("label_fullme_2")
        self.verticalLayout.addWidget(self.label_fullme_2)
        self.label_fullme_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fullme_3.setText("")
        self.label_fullme_3.setPixmap(QtGui.QPixmap(":/imgs/images/fullme/fullme3.jpg"))
        self.label_fullme_3.setScaledContents(True)
        self.label_fullme_3.setObjectName("label_fullme_3")
        self.verticalLayout.addWidget(self.label_fullme_3)
        self.label_fullme_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_fullme_4.setText("")
        self.label_fullme_4.setPixmap(QtGui.QPixmap(":/imgs/images/fullme/fullme4.jpg"))
        self.label_fullme_4.setScaledContents(True)
        self.label_fullme_4.setObjectName("label_fullme_4")
        self.verticalLayout.addWidget(self.label_fullme_4)

        self.retranslateUi(fullme_window)
        QtCore.QMetaObject.connectSlotsByName(fullme_window)

    def retranslateUi(self, fullme_window):
        _translate = QtCore.QCoreApplication.translate
        fullme_window.setWindowTitle(_translate("fullme_window", "Form"))
import code_rc
